Repository 0tuedon/Team-Samurai-Tours-Project, pull requests merged in 2021-11, with the labels that each got.

#11 Fixed the Unused Variables in the App.js
  .gitignore
  .ionide/symbolCache.db
  src/App.js
Labels: bug

#22 Built the Ui for Tours Component Included Every Button and Styling
  src/App.js
  src/components/Body/Tour.css
  src/components/Body/Tour.jsx
  src/index.css
Labels: enhancement

#23 State inital creation
  src/components/Body/Tour.jsx
Labels: enhancement

#26 Loop the Data gotten from the endpoint
  src/components/Body/Tour.css
  src/components/Body/Tour.jsx
  src/components/Body/Tourcard.jsx
  src/index.css
Labels: enhancement

#27 'Fixed Unused Var'
  src/components/Body/Tour.jsx
  src/components/Body/Tourcard.jsx
Labels: duplicate, enhancement
